### ISSUE TITLE
stuck with noob

### ISSUE THREAD

**Issue by pyisme** [1Revenger1/X1-Extreme-OpenCore-Resources#2]
![94736639_1472568999571594_6453960992496812032_o](https://user-images.githubusercontent.com/64273082/80571477-e397fb00-8a26-11ea-989c-a02b2f56bda7.jpg)

**Comment by pyisme** [comment]
can you help me with this?

**Comment by averycblack** [comment]
Uhhh, Make sure you're adding SSDT-BATT
And that it's enabled.
I don't really do installation support over github issues. Best place is likely on the r/Hackintosh discord server. I"m 1Revenger1 on there.
